### ISSUE TITLE
Connecting to multiple headsets from same computer

### ISSUE THREAD

**Issue by sunshineinsandiego** [krigolson/uvicMuse#1]
Hi - Does uvicMuse allow for streaming data from multiple headsets simultaneously and recording to the same labrecorder instance?  Or would we need to run multiple instances of the program from multiple terminals and connect each to a different labrecorder instance? Thanks!

**Comment by krigolson** [comment]
You need multiple instances


Olav Krigolson, PhD

Professor

Check out my TEDx talk - How Mobile EEG Will Change Our World!
<https://www.youtube.com/watch?v=QOcFzJSqfQ0&t=2s>

Theoretical and Applied Neuroscience Laboratory
www.krigolsonlab.com

Affiliations:
Neuroscience Program
Department of Psychology
School of Exercise Science

Email: ***@***.***
Phone:  250 721 7843
Fax:   250 721 6601
Office: McKinnon 187

Mailing Address:
PO Box 1700 STN CSC
University of Victoria
Victoria, British Columbia
Canada
V8W 2Y2

**Comment by sunshineinsandiego** [comment]
Got it, thank you!
